name: 🧪 Run Unit Tests

on: [push, pull_request]

jobs:
  Tests:
    name: Run All Tests on 3.5.1
    runs-on: ubuntu-latest
    container: barichello/godot-ci:mono-3.5.1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          cd godot
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug

      - name: Compile
        run: |
          cd godot
          msbuild

      - name: Run
        run: |
          cd godot
          godot addons/WAT/cli.tscn run=all

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: godot/tests/results.xml
